"""empty message

Revision ID: 34d33b7d13f8
Revises: 
Create Date: 2018-02-10 04:16:31.279322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d33b7d13f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=21), nullable=True),
    sa.Column('building_num', sa.Integer(), nullable=True),
    sa.Column('floor_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toilets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flush_volume', sa.Integer(), nullable=True),
    sa.Column('big_small', sa.Boolean(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('cluster_pos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flushes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('toilet_id', sa.Integer(), nullable=True),
    sa.Column('flush_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flushes')
    op.drop_table('toilets')
    op.drop_table('clusters')
    # ### end Alembic commands ###
