"""empty message

Revision ID: dda7238b3670
Revises: 34d33b7d13f8
Create Date: 2018-02-10 04:26:16.328071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda7238b3670'
down_revision = '34d33b7d13f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toilets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flush_volume', sa.Integer(), nullable=True),
    sa.Column('big_small', sa.Boolean(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('cluster_pos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'flushes', 'toilets', ['toilet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flushes', type_='foreignkey')
    op.drop_table('toilets')
    # ### end Alembic commands ###
